### ISSUE TITLE
21:00:00 isn't number?

### ISSUE THREAD

**Issue by coolshing** [corentingosselin/ProdigyNightclubWiki#16]
I use Minecraft 1.16.5.When I entered  **/pnc event create 1 buy test 29/12/2021 03:00:00 11/11/2022 10:00:00 30 -1** , the system says
Error: 21:00:00 must be a number.Is my enter wrong arg?
![Image 1](https://user-images.githubusercontent.com/79793171/147599981-27e38625-8021-49d6-90bb-bea36bd8ee39.png)

**Comment by corentingosselin** [comment]
Hello, 

First try to not be inside your nightclub when you execute this command.
Or execute this command if you want to be inside your nightclub:
/pnc event create buy test 29/12/2021 03:00:00 11/11/2022 10:00:00 30 -1 

If this is not working:
Is your nightclub named "1", if yes you should probably rename it ! this could cause issues
You can do that by stopping your server, then go into your nightclub.yml and rename the 1 to any name with letter

**Comment by coolshing** [comment]
> Hello,
> 
> First try to not be inside your nightclub when you execute this command. Or execute this command if you want to be inside your nightclub: /pnc event create buy test 29/12/2021 03:00:00 11/11/2022 10:00:00 30 -1
> 
> If this is not working: Is your nightclub named "1", if yes you should probably rename it ! this could cause issues You can do that by stopping your server, then go into your nightclub.yml and rename the 1 to any name with letter

ok! I get it. I will try this later. Thanks your help

**Comment by coolshing** [comment]
By the way, this plugin can support 1.18?

**Comment by corentingosselin** [comment]
> By the way, this plugin can support 1.18?

Yes I need to work on that
