### ISSUE TITLE
Duplicatet Effect

### ISSUE THREAD

**Issue by TastaMax** [corentingosselin/ProdigyNightclubWiki#17]
When you create an effect, there are 2 in the game at once. Also the position of the effect is wrong.
After saving the effect, the position is correct, but the head remains from the wrong one.

Server Version 1.18.2 Paper

![Bild_2022-03-18_105019](https://user-images.githubusercontent.com/25503461/158980552-8f089039-8c56-429c-9c2a-99b5810d8ea3.png)

**Comment by corentingosselin** [comment]
I can't reproduce this bug, can you provide me some commands you did to get that one ?
