### ISSUE TITLE
Plugin doesn't work and can't connect to server

### ISSUE THREAD

**Issue by TymonLC** [corentingosselin/ProdigyNightclubWiki#2]
https://prnt.sc/12qkph0
all plugins (protocol lib) are working 
https://prnt.sc/12qkq5v
What's the problem?  I want add my test server, after add NightClub still doesn't work, i can't connect to it (server is on titanaxe) All Servers are 1.16.5, i don't know, please help

**Comment by TymonLC** [comment]
I looking to console , i copy logs:
>.... [00:29:11 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
>.... [00:29:14 WARN]: Legacy plugin ProtocolLib v4.4.0 does not specify an api-version.
>.... [00:29:15 INFO]: [ProtocolLib] Loading ProtocolLib v4.4.0
>.... [00:29:15 WARN]: [ProtocolLib] Version (MC: 1.16.5) has not yet been tested! Proceed with caution.
>.... [00:29:15 WARN]: [ProtocolLib] [PacketFilterManager] Cannot load server and client packet list.
****>.... [00:29:15 WARN]: [ProtocolLib] Failed to register command PACKET: java.lang.ExceptionInInitializerError****

**Comment by corentingosselin** [comment]
Hello, can you provide me your spigot name :)

**Comment by TymonLC** [comment]
v_Max_v

**Comment by NeadApTar** [comment]
@TymonLC  Update ProtocolLib.... You are running version 4.4.0 of 2018 which is for 1.13. Last version is 4.6.0, plugin work perfectly https://www.spigotmc.org/resources/protocollib.1997/update?update=387702

**Comment by corentingosselin** [comment]
And you have 2 protocollibs plugin inside your server. The server can't load 2 same plugin.
