### ISSUE TITLE
The error from console

### ISSUE THREAD

**Issue by coolshing** [corentingosselin/ProdigyNightclubWiki#26]
I use the server core of paper-1.19.3.jar:git-Paper-448. When I put this plugin into the plugin folder, the error is shown from console. How can fix it?
[error.txt](https://github.com/corentingosselin/ProdigyNightclubWiki/files/11041829/error.txt)

**Comment by corentingosselin** [comment]
Hello, your rotation configuration is invalid,

you must place minimum and maximum random number.
Like: -1;1 and not 1;-1

**Comment by coolshing** [comment]
oh I get it, thanks 
One more question, why it appears this message in command_block? I remember I asked this question before, but I forget how it uses
![image](https://user-images.githubusercontent.com/79793171/227213424-18a06b54-d38f-48a5-b60c-3810312947f4.png)

**Comment by corentingosselin** [comment]
Pnc projector rotation nightclubname rotationname group/ids/id

**Comment by coolshing** [comment]
t

> Pnc projector rotation nightclubname rotationname group/ids/id

thanks your help :D
