### ISSUE TITLE
Barmen skin sometimes is steve/alex

### ISSUE THREAD

**Issue by NeadApTar** [corentingosselin/ProdigyNightclubWiki#5]
If I go from point A to point B, the skin is not loaded, but if I go from point C to D, for example, everything is OK. So, if you approach from the front to get into the field of view of the NPC, the skin will appear.
<details>
<summary>Image</summary>

 ![image](https://user-images.githubusercontent.com/34768994/118554556-43fcf600-b76a-11eb-815b-3bfed2335c02.png)
<details>

**Comment by corentingosselin** [comment]
Well, I think this is not related to the movement.
Something I don't understand is c to d because the nightclub area should be bigger enough  to prevent the barman despawning

But yeah I noticed this bug, I will look into.

**Comment by corentingosselin** [comment]
This bug appears sometimes when I reload the server 
But can't reproduce it frequently

**Comment by NeadApTar** [comment]
It is strange, but every time after restarting the server/plugin (I use [ServerUtils](https://www.spigotmc.org/resources/serverutils-bungeecord-spigot-manage-plugins-in-game-plugman-alternative-more.79599/)) and if you are inside the club and with your back to the barmen of blocks 6+ (don't look at the NPC through F5), then the skin is not displayed. In all 10+ cases of restart, I reproduce the bug.
![image](https://user-images.githubusercontent.com/34768994/120906845-8331af00-c665-11eb-9474-5eb0c953053f.png)

**Comment by corentingosselin** [comment]
Don't use a plugin to reload prodigynightclub like plugman or serverutils
Always use /pnc reload if you change some config file or restart the server :)
