### ISSUE TITLE
Fog/Smoke effect & startup file

### ISSUE THREAD

**Issue by NeadApTar** [corentingosselin/ProdigyNightclubWiki#6]
I think this effect would be cool to add :D
And, I would like to be able to run the scenario automatically when the plugin/server starts. Also when will be possible to add effects to the scenario? I would also like to be able to change the size of the cube, etc.
<details>
<summary>Images</summary>

![fog](https://user-images.githubusercontent.com/34768994/120905553-8aec5600-c65b-11eb-88a0-f1ab6513e791.gif)
![fog2](https://user-images.githubusercontent.com/34768994/120905745-dfdc9c00-c65c-11eb-86a0-e2fbcd50e6ce.gif)
</details>

Maybe some file called `startup.yml` and in this format?
```yml
scenarios:
  - test
effects:
  - cube 0
  - dome 1
# etc
```

**Comment by corentingosselin** [comment]
The effect for scenario will come soon, 
Concerning starting the scenario on server starts, you can do it via another plugin, but I will consider adding this feature


For that smoke effect you are asking you should be able to do that with effect called particle but I will change some option to make it easier to configure
You can already configure the radius of dome, pyramid and cube, check effect.yml after setting it

**Comment by NeadApTar** [comment]
The radius changes the number of particles from point A to point B. For example, the radius is 5, the cube line will have 5 points of particles, and if you put the radius 8, then there will be 8 particles on this line.  I need to resize the cube, etc.  I don’t know how else to explain, but you cannot change the size now. Maybe I did something wrong, but I couldn't change the size through `radius`.

 And you cannot run the effect from the console or other plugin, only the player can execute the command.

**Comment by corentingosselin** [comment]
Thank you for your report, I will reupload an update soon to fix the both bugs

**Comment by corentingosselin** [comment]
issues fixed, I made a silent update, just download the latest version
