### ISSUE TITLE
change what the bar serves

### ISSUE THREAD

**Issue by McLovinnnn** [corentingosselin/ProdigyNightclubWiki#9]
Is there a way i can change what the bar serves?

**Comment by corentingosselin** [comment]
Hello, I don't understand your question ?

**Comment by NeadApTar** [comment]
I think he means if is an option to change the items that the barmen gives 🤔🤔🤔

**Comment by corentingosselin** [comment]
> I think he means if is an option to change the items that the barmen gives 🤔🤔🤔

There is no option to change the value of the item, but you can change the language.
